# This playbook is meant to be an all-in-one
- name: Run the ostree update in a single play without external deps
  become: true
  hosts: localhost
  vars:
    fleet_infra_env: "@@ .FleetInfraEnv @@"
    update_number: "@@ .UpdateNumber @@"
    s3_region: "@@ .BucketRegion @@"
    s3_buckets:
      prod: "rh-edge-tarballs-prod"
      stage: "rh-edge-tarballs-stage"
      perf: "rh-edge-tarballs-perf"
    repo_url: "https://{{ s3_buckets[fleet_infra_env] | default('rh-edge-tarballs-prod') }}.s3.{{ s3_region | default('us-east-1') }}.amazonaws.com/{{ update_number }}/upd/{{ update_number }}/repo"
    ostree_remote_name: "@@ .GoTemplateRemoteName @@"
    ostree_changes_refs: "@@ .RemoteOstreeUpdate @@"
    os_tree_ref: "@@ .OSTreeRef @@"
    ostree_gpg_verify: "false"
    ostree_gpg_keypath: "/etc/pki/rpm-gpg/"
    ostree_remote_template: |
      [remote "{{ ostree_remote_name }}"]
      url={{ repo_url }}
      gpg-verify={{ ostree_gpg_verify }}
      gpgkeypath={{ ostree_gpg_keypath }}
      contenturl={{ repo_url }}
    insights_signature_exclude: "/vars/insights_signature,/vars/fleet_infra_env,/vars/update_number,/vars/s3_region,/vars/ostree_remote_name,/vars/ostree_changes_refs,/vars/os_tree_ref"
    insights_signature: !!binary |
      TFMwdExTMUNSVWRKVGlCUVIxQWdVMGxIVGtGVVZWSkZMUzB0TFMwS1ZtVnljMmx2YmpvZ1IyNTFV
      RWNnZGpFS0NtbFJTVlpCZDFWQldYUkJjVlZOZG5jMU9FUXJhalZ3VGtGUmFWQmlVUzh2V0dobmRX
      dFNNRzlWT0hrd2VFMW1TMFl5SzJRNFVFbHdOVXhyYTJWakwyTUtOV0pNU0ZoeldrZzRTMGxxVG5S
      bmNIUTBXRkJJV1hZeU9VWnlSamRNVlRKVWFFUjNTSGRHY1c1UVJVNUNTbTF1ZEdjNVVVcE9ZMWRL
      VkV3cmVGVnBXUXBHVEc4clNIZHpTRlE1ZUhNNFpIWmpWMUpHYVVOdVVteEtUekF5YTNsYVNWVk1i
      amRYVG5NcmVXeFVjbHByVUdSblNYaGFUMlkwS3pkWVozSTFTVmxzQ25WM1l6TmxjMkZMYzBNNFF6
      SklXV2Q0TURWVmFsVTFPRVF5WkZwUVYzTnpRazVCUTFSUk1VeHVXa0prZWt0YU5ISlJVbkZYVmk5
      SVVtaDFTelEzS3pZS05YaHZjbmxTVkVORk4yaFFWMjVhVkZOMGNEaEJhSFozVDBSMlVFRkVWVnBo
      UjNacEt6Wk9jbEZFV0RKQ1VERnZaRFF4SzFwR1ZYbHVRMmxIWldSdlJBcHVha2tyY1VsUVNEQlBi
      bWxRUWxWSlduWXJhSE5pTVRWdVQydEtVVVZ0V1RaVGJuWlhVR3hrWlVwQmNGZHRXalZyT0ZoQ1Ru
      Qk5jalJQVFVWRU56aDRDa05zVldrMFdsRjVhRWRTWW5nek5EQmFRekpSWWtrdmVXWXpialJITmt4
      TVEwcFBaVWt2Tm5CdldGSktSbE5EYVdreFZVVjZMM1JFVW1oMWFHeFNkbElLTlZGMmIzVlNTalp4
      UlZRNVJFSlVheXQwZGxBNFoySklkbWQxZUUxTmFsaFVaMlZuTkZsWFVqVlRTVmRMZERkd1kzZFNV
      bXhDVERKQ1dqQnpOSHB2T1FwM1FtMDJVRUk0WTNOTmJIcHpNR2hPWkhoeU5EbGtNWFZRWkhWTVVF
      TjZUbWR0VjJwVmNscGFRelV3TkhwMFpFSmhUR1V2YVd0RlowczFNR1k1Y2psekNtSXJZWEJpYVZS
      QmVtcHdTMk4xTVdwUU9IWkhXRFpyTTJGb00zUnpkRFZZY2t0R1V6VlBiM0Z3YnpBeVNEUldjSGxQ
      VWxob1dpODFLM1V5VFdOSE5XNEtLMmt6V0d4YVlUWlRaVlJ1VWpkTWNFaE9iblk1Ymk4Mk9URnFW
      VU5sZG1wRlZYVmhNR2RzWlU1M01qUmhNSGM0ZDJ3clduTjNOSGNyYW5BMVYxcHZaUW93WlRsM2FF
      WmFabU51VFQwS1BYWnBhMDRLTFMwdExTMUZUa1FnVUVkUUlGTkpSMDVCVkZWU1JTMHRMUzB0Q2c9
      PQ==
  tasks:
    - name: apply templated ostree remote config
      ansible.builtin.copy:
        content: "{{ ostree_remote_template }}"
        dest: /etc/ostree/remotes.d/rhel-edge.conf
    - name: run rpmostree update
      when: not ostree_changes_refs|bool
      ansible.builtin.shell: rpm-ostree upgrade --allow-downgrade
      register: rpmostree_upgrade_out
      changed_when: '"No upgrade available" not in rpmostree_upgrade_out.stdout'
      failed_when: 'rpmostree_upgrade_out.rc != 0'
    - name: run rpmostree rebase
      when: ostree_changes_refs|bool
      ansible.builtin.shell: rpm-ostree rebase "{{ os_tree_ref }}"
      register: rpmostree_rebase_out
      changed_when: '"No upgrade available" not in rpmostree_rebase_out.stdout'
      failed_when: 'rpmostree_rebase_out.rc != 0'
    - name: schedule reboot when rpmostree upgraded
      ansible.builtin.shell: systemd-run --on-active=5 /usr/bin/systemctl reboot
      when: ('rpmostree_rebase_out.changed | "Staging deployment...done" in rpmostree_rebase_out.out') or ('rpmostree_upgrade_out.changed | "Staging deployment...done" in rpmostree_upgrade_out.stdout')
