# This playbook is meant to be an all-in-one
- name: Run the ostree update in a single play without external deps
  become: true
  hosts: localhost
  vars:
    fleet_infra_env: "dev"
    update_number: "1000"
    s3_region: "us-east-1"
    s3_buckets:
      prod: "rh-edge-tarballs-prod"
      stage: "rh-edge-tarballs-stage"
      perf: "rh-edge-tarballs-perf"
    repo_url: "https://{{ s3_buckets[fleet_infra_env] | default('rh-edge-tarballs-prod') }}.s3.{{ s3_region | default('us-east-1') }}.amazonaws.com/{{ update_number }}/upd/{{ update_number }}/repo"
    ostree_remote_name: "remote-name"
    ostree_changes_refs: "false"
    os_tree_ref: "rhel/8/x86_64/edge"
    ostree_gpg_verify: "false"
    ostree_gpg_keypath: "/etc/pki/rpm-gpg/"
    ostree_remote_template: |
      [remote "{{ ostree_remote_name }}"]
      url={{ repo_url }}
      gpg-verify={{ ostree_gpg_verify }}
      gpgkeypath={{ ostree_gpg_keypath }}
      contenturl={{ repo_url }}
    insights_signature_exclude: "/vars/insights_signature,/vars/fleet_infra_env,/vars/update_number,/vars/s3_region,/vars/ostree_remote_name,/vars/ostree_changes_refs,/vars/os_tree_ref"
    insights_signature: !!binary |
      TFMwdExTMUNSVWRKVGlCUVIxQWdVMGxIVGtGVVZWSkZMUzB0TFMwS1ZtVnljMmx2YmpvZ1IyNTFV
      RWNnZGpFS0NtbFJTVlpCZDFWQldYTm9NM1JqZG5jMU9FUXJhalZ3VGtGUmFrdzRVUzh2WmxCcVJs
      SlljVkJMSzJGU01HVjRRM2xPTjNwRVozRjRXbVp4TVVadE9YWUtaMjV3Wm14U1RFZERibVJPWWtw
      UGEwRk9lWE5CUTNKblNtRlNlVFpMYVdvMVJIZHFNR1JsY0ZoRFp6Ulhha2hGVW0xcVJEQlhSRVJL
      UVd3Mk9XMU1SQXBpY1dodFoxZ3Jiemx4Wm5SM09UVmpZbFI1VlN0bFpUZDJSVFZxVGxSRU1GQXpZ
      VXhhZW1GNk4wWlpOWHBhTlc1NmRVZ3JlRmhOYkZoUmFrdDFPSGd3Q205UlJYUm9VbE5EUlVSdk5r
      eDBNWG81UW04d1VuSlRZUzlyWTIxQ1owWTVPVVl4Wms5Q1duTm1aeTloWXlzME4zUTNNemx1YlRZ
      elRYQklSbTFKVWtjS2FXSkhibUZHYWtaMmJYTkpkVFJMZVVkMlFXdEVUblEwZEdKME4yMUJObXBp
      VFhsTVVuaGxRbTV0WjIxeVp6SkVaM001VUZaM2NXbFdaV1JTUlZoNWRRcHdjbUV6WTJ4bGRYWm1N
      bFJ1TUVsNVQwUjRiMGxJWXpGWFIwOU5SRGxNV2pkVE5YVnlNMVJyYVdaeWFGWlJXRkoyZUdsS05X
      UlBjak42VUVsaU1IWkNDbkJTVUhwb1ZsUlpRbEZ6YzA5MFpXZ3lZMGRVUnpKTE1VTkJNakZXVGtw
      V1ltcHRSMGxtYjBoT2RGaHNkRFJ1YjA5TmRuazBka1pzUkdaak16QkdOa1lLV0VaV2JsZDJlbFE1
      TURSdVpUbDJlRzlTYTJaVkwxSTVOR016VW5jelpHa3JRMWh3Y25ZM2JrVk1NalJsZWxoUmFrdHFh
      bTlUV25FMGNFbDFUR04zVlFvd1QwRTJVRGRpWkZScmRHMDBjRnBuYVZrNWQySnJXSFZVVTFjME5W
      RlJjVUpKY1dkbFIwNTJZMVJIYWk5U2RVRm9ObXBxUlUxTVpYRjJWV0owVDBwRkNrUnNTRVI1VlU0
      dmRrSm9VRXRFVUc5SFZWQXdWM0ZuU0hGaFZsTllaMmxtTTBrdlJYbE5ibk5qVXpKcGVVMTNMelow
      TWk5V1QyNXVXV2hUYTJsdk5FZ0thM2RZZG0xRmFTdFNlVm94UTJOSVFXa3ljSE5pZERnNFZFVjZj
      SEo2UVZOWEx6UTFSekpFVUdReksyNHlUMnhxZFU4eU0wSTJNemx5WTI1SVoxQlNTQXB1UVRsdFdH
      cEtaR0ZZT0QwS1BUSm5TVE1LTFMwdExTMUZUa1FnVUVkUUlGTkpSMDVCVkZWU1JTMHRMUzB0Q2c9
      PQ==
  tasks:
    - name: apply templated ostree remote config
      ansible.builtin.copy:
        content: "{{ ostree_remote_template }}"
        dest: /etc/ostree/remotes.d/rhel-edge.conf
    - name: run rpmostree update
      when: ostree_changes_refs=="false"
      ansible.builtin.shell: rpm-ostree upgrade --allow-downgrade
      register: rpmostree_upgrade_out
      changed_when: '"No upgrade available" not in rpmostree_upgrade_out.stdout'
      failed_when: 'rpmostree_upgrade_out.rc != 0'
    - name: run rpmostree rebase
      when: ostree_changes_refs=="true"
      ansible.builtin.shell: rpm-ostree rebase "{{ os_tree_ref }}"
      register: rpmostree_upgrade_out
      changed_when: '"No upgrade available" not in rpmostree_upgrade_out.stdout'
      failed_when: 'rpmostree_upgrade_out.rc != 0'
    - name: schedule reboot when rpmostree upgraded
      ansible.builtin.shell: systemd-run --on-active=5 /usr/bin/systemctl reboot
      when: '"Staging deployment...done" in rpmostree_upgrade_out.stdout'
